// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzZygbuNzocNQMUb1RVh_W4NGAu5U-m4',
    appId: '1:741787806515:android:1e6eff3b0df4b32e1cac46',
    messagingSenderId: '741787806515',
    projectId: 'ui-bardi',
    storageBucket: 'ui-bardi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiUs5jPVmxYivOIDAA3SNxyC8_rTZIiZY',
    appId: '1:741787806515:ios:2a40d491db59000d1cac46',
    messagingSenderId: '741787806515',
    projectId: 'ui-bardi',
    storageBucket: 'ui-bardi.appspot.com',
    androidClientId: '741787806515-2pepb0bp1hr1nea3goth6k0rvbf1t9ng.apps.googleusercontent.com',
    iosClientId: '741787806515-63tbhklbfpoembhisu7rr7j20mb6p2b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiBardi',
  );
}
